// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRu7Az8HtYppSMjaLy2fNncmeX1XV9RrI',
    appId: '1:338668991304:web:e6256dc53471ac6b14397d',
    messagingSenderId: '338668991304',
    projectId: 'toodoos-ff88c',
    authDomain: 'toodoos-ff88c.firebaseapp.com',
    storageBucket: 'toodoos-ff88c.firebasestorage.app',
    measurementId: 'G-ZC8TYD4LNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjfskD_tTaYCcrNWzWkTsYgdhQ1bbRw0I',
    appId: '1:338668991304:android:7492d9eb641a85d314397d',
    messagingSenderId: '338668991304',
    projectId: 'toodoos-ff88c',
    storageBucket: 'toodoos-ff88c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUIYsNs-9CDPbdQoxyi-z5g6bHhx92Bjo',
    appId: '1:338668991304:ios:d186f134498c0b1814397d',
    messagingSenderId: '338668991304',
    projectId: 'toodoos-ff88c',
    storageBucket: 'toodoos-ff88c.firebasestorage.app',
    iosBundleId: 'com.example.flutter20Start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUIYsNs-9CDPbdQoxyi-z5g6bHhx92Bjo',
    appId: '1:338668991304:ios:d186f134498c0b1814397d',
    messagingSenderId: '338668991304',
    projectId: 'toodoos-ff88c',
    storageBucket: 'toodoos-ff88c.firebasestorage.app',
    iosBundleId: 'com.example.flutter20Start',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRu7Az8HtYppSMjaLy2fNncmeX1XV9RrI',
    appId: '1:338668991304:web:0d37bc882cadfd9d14397d',
    messagingSenderId: '338668991304',
    projectId: 'toodoos-ff88c',
    authDomain: 'toodoos-ff88c.firebaseapp.com',
    storageBucket: 'toodoos-ff88c.firebasestorage.app',
    measurementId: 'G-J46H10LWWL',
  );
}
